version: "3"

services:
  ckan:
    user: root
    stdin_open: true
    tty: true
    entrypoint: '/bin/bash /dev-entrypoint.sh'
    command: 'bash -c "source /usr/lib/ckan/venv/bin/activate && python -m pdb /usr/lib/ckan/venv/bin/ckan -c /etc/ckan/production.ini run --host 0.0.0.0 --disable-reloader --passthrough_errors"'
    volumes:
      - ./ckanext/ckanext-branding:/usr/lib/ckan/venv/src/ckanext/ckanext-branding
